require:
  - rubocop-rspec
  - rubocop-rails

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
